const char *header[29] =
{
    "SIMPLE  =                    T",
    "BITPIX  =                   16",
    "NAXIS   =                    2",
    "NAXIS1  =                 2184",
    "NAXIS2  =                 1472",
    "BZERO   =                32767",
    "BSCALE  =                    1",
    "OBSERVER=",
    "DATE    = '2014-11-04T12:55:43'",
    "DATE-OBS= '2014-11-04T12:55:32'",
    "INSTRUME=",
    "COLORCCD=                    0",
    "EXPOSURE=                    0",
    "XBINNING=                    1",
    "YBINNING=                    1",
    "XPIXSZ  =                    0",
    "YPIXSZ  =                    0",
    "FOCALLEN=                    0",
    "APERTURE=                    0",
    "FILTER  =",
    "CCD-TEMP=                    0",
    "SAT_LEVE=                50000",
    "GAIN    =                    2",
    "PEDESTAL=                  100",
    "RDNOISE =                   9",
    "COMMENT = created by CCDX",
    "CALIBRAT=                    0",
    "END",
    ""
};
